### ISSUE TITLE
Wrong operation on default exchange

### ISSUE THREAD

**Issue by johanrhodin** [cloudamqp/amqpcat#2]
After "support for decalring[sic] exchanges, with exchange type" the hello world example is broken:
```$ echo Hello World | bin/amqpcat --producer --uri=$CLOUDAMQP_URL --queue test
403 - ACCESS_REFUSED - operation not permitted on the default exchange

**Comment by carlhoerberg** [comment]
Fixed in https://github.com/cloudamqp/amqpcat/commit/06897d58cf79c3f8ba489580cdda1f6641604f5c
