### ISSUE TITLE
Output each message into a new file

### ISSUE THREAD

**Issue by thomaspeissl** [cloudamqp/amqpcat#8]
Hi,
I'm using this command from the examples:
`amqpcat --consumer --uri=$CLOUDAMQP_URL --queue test --format "%e,%r,"%s"\n | tee messages.csv`

Can I somehow create a new file for each incoming message (instead of appending to a single file)?
Eg. `| tee logfile_$(date '+%Y-%m-%d_%T_%N').json` (this obviously doesn't work)

**Comment by carlhoerberg** [comment]
You could use `xargs` to achieve it: 

```sh
amqpcat --consumer --uri=$CLOUDAMQP_URL --queue test --format "%e,%r,"%s"\n | \
  xargs -I{} sh -c "echo {} | tee logfile_$(date '+%Y-%m-%d_%T_%N').json"
```
